### ISSUE TITLE
Too explicit

### ISSUE THREAD

**Issue by cemkalyoncu** [ahmadqasembader/physics-engine#5]
1. Scope resolution will make your life very, very difficult if you need to rename your class. Use this-> instead
2. In setters, instead of using SetAcceleration(Point acceleration) use SetAcceleration(Point value). This way, you won't even need this->

https://github.com/ahmadqasembader/physics-engine/blob/d1b3315d60a2b71f1d00f84424eb7fd57fa52d7f/particle.cpp#L119

**Comment by ahmadqasembader** [comment]
Done
